### ISSUE TITLE
Best bordered path selection

### ISSUE THREAD

**Issue by gungoren** [cuSTEMized/Connect-The-Dots-Generator#1]
I have looked your source code it selected first path child of svg for generating dots. But most svg files first path child is not border of figure? I think it needs to be a little bit improved for selecting best choice path which contains border of figure.

**Comment by janet-yu** [comment]
Hello gungoren,

Thank you for bringing attention to his issue! I have managed to fix this problem in commit 72b3eb2 where I added a path selector to the page that allows you to choose the path you want as the main 'connect the dots' path.  

This was done by adding a select element to the HTML and binding it to a new function called 'changePath' that is invoked whenever the user chooses a new path from the path selector. This 'changePath' function re-initializes the current 'path' variable to the path the user selected, then calls the draw function to update the SVG and draw the chosen path onto the SVG image.
